# Generated by Django 3.2.3 on 2021-06-12 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210609_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
