# Generated by Django 3.2.3 on 2021-06-12 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_marker_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='user',
        ),
        migrations.AddField(
            model_name='marker',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
