# Generated by Django 3.2.3 on 2021-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210612_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='markers',
            field=models.ManyToManyField(to='accounts.Marker'),
        ),
    ]
