# Generated by Django 3.2.3 on 2021-06-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210612_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='coordinates',
            field=models.TextField(null=True),
        ),
    ]
